### ISSUE TITLE
Reveal H2 Web Console Context

### ISSUE THREAD

**Issue by cconnar** [DecisionsDev/odm-ondocker#175]
Please bundle the H2 web console and provide the context to access the DB contents.

**Comment by lgrateau** [comment]
@cconnar Do you have a pull request to submit ?

**Comment by cconnar** [comment]
@lgrateau I do not, although it's not for a lack of trying.  The web console is a fantastic out of the box feature of H2 that allows for accessing the filesystem DBs and writing SQL against them.  

The ODM standalone is running H2 by default, but it seems the web console is not enabled in a Spring config somewhere or the URI isn't registered with Liberty.  In either case, I am unsure of how to proceed.
