### ISSUE TITLE
Add in the README that we should use the latest version of websphere-liberty webProfile7

### ISSUE THREAD

**Issue by rachel-orti** [DecisionsDev/odm-ondocker#195]
Add in the README that we must use the latest version of websphere-liberty webProfile7. If we do not use the latest version when building the ODM Docker images, we may have some issues that prevent the ODM components to work properly.

**Comment by lgrateau** [comment]
Yes correct. Before performing a build of the docker images, you should ensure that the liberty docker image is up2date. docker pull websphere-liberty:webProfile7 do the job. @rachel-orti do you have tried the docker-compose build --no-cache when you have encournetered this issue ?
