### ISSUE TITLE
[Documentation on DockerHub] Add statement on Eclipse version to use with the plugin

### ISSUE THREAD

**Issue by xrissot-ibm** [DecisionsDev/odm-ondocker#199]
In the "Rule Designer development environment for ODM developers:" section  of the [DockerHub page](https://hub.docker.com/r/ibmcom/odm) we read that we have to use Eclipse v4.7.3. but we don't know if this is the only version of Eclipse that works and/is supported.
What if I use another version?

**Comment by varnem2** [comment]
See the different branches:
https://github.com/ODMDev/ruledesigner
I believe each version of ODM has a plugin for a specific version of eclipse.  Other versions of eclipse are supported with different versions of ODM, but you'll loose functionality.

It is still unclear to me if ODM v8.10.2 supports say Eclipse v3.7, but I've always found it best practice to keep different versions totally separate and downloading exact versions of software.
