### ISSUE TITLE
unable to docker run -e LICENSE=accept

### ISSUE THREAD

**Issue by UltraMel-tech** [DecisionsDev/odm-ondocker#240]
unable to run this command 👍 

docker run -e LICENSE=accept  -m 2048M --memory-reservation 2048M -p 9060:9060 -p 9443:9443 -v $PWD:/config/dbdata/ -e SAMPLE=false  ibmcom/odm:8.10

get 
At line:1 char:96
+ ... --memory-reservation 2048M -p 9060:9060 -p 9443:9443 -v $PWD:/config/ ...
+                                                             ~~~~~
Variable reference is not valid. ':' was not followed by a valid variable name character. Consider using ${} to
delimit the name.
    + CategoryInfo          : ParserError: (:) [], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : InvalidVariableReferenceWithDrive

**Comment by lgrateau** [comment]
@UltraMel-tech what is your OS. Is it Linux/Mac OSX/Windows ?
Thanks Laurent

**Comment by UltraMel-tech** [comment]
windows 10

**Comment by UltraMel-tech** [comment]
![docker error](https://user-images.githubusercontent.com/54663373/81065648-29980780-8edc-11ea-9fb1-e27bdada1c55.PNG)

**Comment by UltraMel-tech** [comment]
my memory on my windows pc is 2g

**Comment by lgrateau** [comment]
thanks you should replace $PWD or by the absolute path of your directory. For exemple : c:\
In the cmd you copy paste you have forget -v c:\:/config/dbdata.
So  you can try something like that 
```javascript
docker run -e LICENSE=accept  -m 2048M --memory-reservation 2048M -p 9060:9060 -p 9443:9443 -v c:/data:/config/dbdata/ -e SAMPLE=false  ibmcom/odm:8.10
```
Sorry but i have not a windows machine so i cannot test it.
