### ISSUE TITLE
Weird error with command from #240

### ISSUE THREAD

**Issue by varnem2** [DecisionsDev/odm-ondocker#268]
When I'm running this command here, with an empty C:/data folder.
```(bash)
docker run -e LICENSE=accept  -m 4096M --memory-reservation 4096M -p 9060:9060 -p 9443:9443 -v c:/data:/config/dbdata/ -e SAMPLE=false  ibmcom/odm:8.10
```
Upon first boot, I'm getting this error.
[odm.log](https://github.com/ODMDev/odm-ondocker/files/6495947/odm.log)
When I log into the Business Console.
```
An error has occurred in trying to access data source 'jdbc/ilogDataSource': Could not lookup datasource named 'jdbc/ilogDataSource'. Check that the data source exists on the application server or contact your administrator.
```

What's odd is during the 2nd boot, it seems fine with clean logs.

If I had to guess, I'd guess that it's trying to create tables it's getting that file lock error. So not all the tables that need to exist exist, and during the 2nd boot some of the table exists so it moves on. Thoughts?

docker version
```
Client:
 Cloud integration: 1.0.14
 Version:           20.10.6
 API version:       1.41
 Go version:        go1.16.3
 Git commit:        370c289
 Built:             Fri Apr  9 22:49:36 2021
 OS/Arch:           windows/amd64
 Context:           default
 Experimental:      true

Server: Docker Engine - Community
 Engine:
  Version:          20.10.6
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.13.15
  Git commit:       8728dd2
  Built:            Fri Apr  9 22:44:56 2021
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.4.4
  GitCommit:        05f951a3781f4f2c1911b05e61c160e9c30eaa8e
 runc:
  Version:          1.0.0-rc93
  GitCommit:        12644e614e25b05da6fd08a38ffa0cfe1903fdec
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0
```

**Comment by lgrateau** [comment]
1/ Does docker is allowed to access to this directory ?
At least on mac osx, there is some popup asking to give priviledge to docker to access this directory.

2/ Could you tried to:
1. Create a directory c:\data1
2. Using this c:\data1 in the docker run cmd
Thanks,

**Comment by varnem2** [comment]
Of course! 

1. Yes, it does. I accepted the popup (on windows as well) and even have the directory listed inside of the docker engine.
2. I'm able to consistently recreate the issue no matter the directory. This always happens with a fresh directory the first time it boots. The second time it boots it works fine.

If it's not recreatable it might just be the antivirus on my machine (I have a few running), but I wonder if it's related to not working inside of a docker volume.
