### ISSUE TITLE
Docker deployment keeps stuck in the graph

### ISSUE THREAD

**Issue by cndingwei** [DecisionsDev/odm-ondocker#295]
Docker deployment keeps stuck in the graph
24 hours
![微信截图_20220118102751](https://user-images.githubusercontent.com/43468679/149867544-d9747407-9eca-4de7-ac47-cfeba53b5cf2.png)

**Comment by eis** [comment]
We see the same thing with linux (ubuntu). On Windows and when using docker desktop it works just fine.
