### ISSUE TITLE
"/executionserver": not found

### ISSUE THREAD

**Issue by hacka0wi** [DecisionsDev/odm-ondocker#351]
[+] Running 1/1
 ! odm-standalone Warning                                                                                                                                       3.7s 
[+] Building 3.7s (10/59)                                                                                                                                            
 => [internal] load .dockerignore                                                                                                                               0.0s
 => => transferring context: 1.51kB                                                                                                                             0.0s
 => [internal] load build definition from Dockerfile                                                                                                            0.0s
 => => transferring dockerfile: 6.47kB                                                                                                                          0.0s
 => [internal] load metadata for docker.io/ibmcom/websphere-liberty:23.0.0.9-kernel-java11-openj9-ubi                                                           3.6s
 => [internal] load metadata for docker.io/library/maven:3.9.3-ibm-semeru-11-focal                                                                              3.4s
 => CANCELED [builder  1/33] FROM docker.io/library/maven:3.9.3-ibm-semeru-11-focal@sha256:641c19ba1c29f19628c3fd72382e163d7d31654ae5dee9d8bbde0a95544fdf91     0.0s
 => => resolve docker.io/library/maven:3.9.3-ibm-semeru-11-focal@sha256:641c19ba1c29f19628c3fd72382e163d7d31654ae5dee9d8bbde0a95544fdf91                        0.0s
 => => sha256:641c19ba1c29f19628c3fd72382e163d7d31654ae5dee9d8bbde0a95544fdf91 979B / 979B                                                                      0.0s
 => => sha256:5629fe2710fb9d366071feaf61ed6638159b64f7e92b422b301c38622772b788 9.50kB / 9.50kB                                                                  0.0s
 => => sha256:4ff1cd79dd81e80644e3ebb70b7765bfae21da69f214f7407023de73cb33f914 2.21kB / 2.21kB                                                                  0.0s
 => [internal] load build context                                                                                                                               0.0s
 => => transferring context: 11.92kB                                                                                                                            0.0s
 => CANCELED [liberty-builder  1/13] FROM docker.io/ibmcom/websphere-liberty:23.0.0.9-kernel-java11-openj9-ubi@sha256:ebc02121716cb030c3e8b2f843bd8911f50cdc56  0.0s
 => => resolve docker.io/ibmcom/websphere-liberty:23.0.0.9-kernel-java11-openj9-ubi@sha256:ebc02121716cb030c3e8b2f843bd8911f50cdc56100193a51e9e7d9a2d613595     0.0s
 => => sha256:1727b970286747293bed2be106105d117fb6cfc66ec05669dae3c622c5b799b6 3.88kB / 3.88kB                                                                  0.0s
 => => sha256:ebc02121716cb030c3e8b2f843bd8911f50cdc56100193a51e9e7d9a2d613595 1.39kB / 1.39kB                                                                  0.0s
 => => sha256:2549b7f1fbc0d9b68cc0a477fc33e15f90bf92e64bf91a55e77b2d9a9be7017f 29.25kB / 29.25kB                                                                0.0s
 => CACHED [builder  2/33] RUN apt-get update && apt-get install unzip                                                                                          0.0s
 => CACHED [builder  3/33] COPY odm-ondocker/decisioncenter/script odm-ondocker/standalone/script odm-ondocker/common/script odm-ondocker/common/features /scr  0.0s
 => ERROR [builder  4/33] COPY ./executionserver/ /executionserver/                                                                                             0.0s
------
 > [builder  4/33] COPY ./executionserver/ /executionserver/:
------
failed to solve: failed to compute cache key: failed to calculate checksum of ref moby::xfhj1x6bw980ua657rreld8xd: "/executionserver": not found

**Comment by alainrobert** [comment]
you need an installation of ODM on Prem to build the image
