### ISSUE TITLE
ODM 9 Docker startup fails ending with java.lang.OutOfMemoryError

### ISSUE THREAD

**Issue by vandermerwewaj** [DecisionsDev/odm-ondocker#360]
Had some trouble using an XSD file, no specific error, just unable to deploy due to an error: at Token """
That was it, the entire error.

Tried a number of restarts, checking for updates (Windows and WSL Debian)
I have since moved away from my previous XSD as I've been informed it'll be discontinued in near future.

Though a new problem haunts me now, my ODM 9 Docker doesn't start up:
CWWKZ0002E: An exception occurred while starting the application decisioncenter. The exception message was: com.ibm.ws.container.service.state.StateChangeException: java.lang.OutOfMemoryError: Java heap space

[error_odm_docker_developer.log](https://github.com/user-attachments/files/17700292/error_odm_docker_developer.log)

**Comment by alainrobert** [comment]
How large is the database you are using now? I noted the option -m 2048M, can you start with -m 4g instead.

**Comment by vandermerwewaj** [comment]
I did increase the size, doubling it.
I also increased the JVM Heap as indicated by the following:
docker run -e LICENSE=accept  -m 4096M --memory-reservation 4096M -p 9060:9060 -p 9443:9443 -e SAMPLE=false -e JAVA_OPTS="-Xms2048M -Xmx2048M"  icr.io/cpopen/odm-k8s/odm:9.0

It seems to go further, but still goes OutOfMemory.
The database is clean, I removed all images and previous containers, starting with a proverbial clean slate.

**Comment by vandermerwewaj** [comment]
I also increased the memory capacity (doubled) available to the WSL distro, that was set to 2048M.

**Comment by vandermerwewaj** [comment]
I did notice while starting the docker image, when trying to access http://localhost:9060 Liberty opens with notification to download latest runtime.

Here is the docker run command: copied from docker:
`docker run 
	--hostname=dff440a21ea3 
	--user=1001 
	--mac-address=02:42:ac:11:00:02 
	--env=LICENSE=accept 
	--env=SAMPLE=false 
	--env=JAVA_OPTS=-Xms2048M -Xmx2048M 
	--env=container=oci 
	--env=LANG=en_US.UTF-8 
	--env=LANGUAGE=en_US:en 
	--env=LC_ALL=en_US.UTF-8 
	--env=PATH=/opt/java/openjdk/bin:/usr/local/sbin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/ibm/wlp/bin:/opt/ibm/helpers/build 
	--env=JAVA_VERSION=jdk-17.0.12+7_openj9-0.46.1 
	--env=JAVA_HOME=/opt/java/openjdk 
	--env=JAVA_TOOL_OPTIONS=-XX:+IgnoreUnrecognizedVMOptions -XX:+PortableSharedCache -XX:+IdleTuningGcOnIdle -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal 
	--env=LOG_DIR=/logs 
	--env=WLP_OUTPUT_DIR=/opt/ibm/wlp/output 
	--env=OPENJ9_SCC=true 
	--env=RANDFILE=/tmp/.rnd 
	--env=OPENJ9_JAVA_OPTIONS=-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal -Dosgi.checkConfiguration=false 
	--env=ODMDOCKERDIR=odm-ondocker 
	--env=APP_NAME=StandaloneOdm 
	--env=SCRIPT=/script 
	--env=APPS=/config/apps 
	--env=CONNECTION_POOL_SIZE=20 
	--network=bridge -p 9060:9060 -p 9443:9443 
	--restart=no 
	--label='BuildLabel=cl240620240603-2001' 
	--label='ProductID=fbf6a96d49214c0abc6a3bc5da6e48cd' 
	--label='ProductName=WebSphere Application Server Liberty' 
	--label='ProductVersion=24.0.0.6' 
	--label='architecture=x86_64' 
	--label='build-date=2024-09-17T13:47:26' 
	--label='com.docker.compose.project=odm-ondocker' 
	--label='com.docker.compose.service=odm-standalone' 
	--label='com.docker.compose.version=2.29.7' 
	--label='com.ibm.websphere.liberty.image.tag=24.0.0.6-kernel-java17-openj9-ubi' 
	--label='com.redhat.component=ubi8-container' 
	--label='com.redhat.license_terms=https://www.redhat.com/en/about/red-hat-end-user-license-agreements#UBI' 
	--label='description=This image contains the WebSphere Liberty runtime with IBM Semeru Runtime Open Edition OpenJDK with OpenJ9 and Red Hat's UBI 8 as the base OS.  For more information on this image please see https://ibm.biz/wl-app-image-template' 
	--label='distribution-scope=public' 
	--label='io.buildah.version=1.33.8' 
	--label='io.k8s.description=The Universal Base Image is designed and engineered to be the base layer for all of your containerized applications, middleware and utilities. This base image is freely redistributable, but Red Hat only supports Red Hat technologies through subscriptions for Red Hat products. This image is maintained by Red Hat and updated regularly.' 
	--label='io.k8s.display-name=Red Hat Universal Base Image 8' 
	--label='io.openshift.expose-services=' 
	--label='io.openshift.tags=base rhel8' 
	--label='java-version=IBM_Semeru_Runtime_Open_Edition_17.0.12.1_(build_17.0.12+7)' 
	--label='liberty.image.tag=24.0.0.6-kernel-java17-openj9-ubi' 
	--label='maintainer=ODMDev odmdev_open_source_user@wwpdl.vnet.ibm.com' 
	--label='name=IBM WebSphere Liberty' 
	--label='org.opencontainers.image.authors=Leo Christy Jesuraj, Thomas Watson, Wendy Raschke, Michal Broz' 
	--label='org.opencontainers.image.description=This image contains the WebSphere Liberty runtime with IBM Semeru Runtime Open Edition OpenJDK with OpenJ9 and Red Hat's UBI 8 as the base OS.  For more information on this image please see https://ibm.biz/wl-app-image-template' 
	--label='org.opencontainers.image.documentation=https://www.ibm.com/support/knowledgecenter/SSAW57_liberty/com.ibm.websphere.wlp.nd.multiplatform.doc/ae/cwlp_about.html' 
	--label='org.opencontainers.image.revision=cl240620240603-2001' 
	--label='org.opencontainers.image.title=IBM WebSphere Liberty' 
	--label='org.opencontainers.image.url=https://github.com/WASdev/ci.docker' 
	--label='org.opencontainers.image.vendor=IBM' 
	--label='org.opencontainers.image.version=24.0.0.6' 
	--label='release=17' 
	--label='run=docker run 
	--rm -ti <image_name:tag> /bin/bash' 
	--label='summary=Image for WebSphere Liberty with IBM Semeru Runtime Open Edition OpenJDK with OpenJ9 and Red Hat's UBI 8' 
	--label='url=https://access.redhat.com/containers/#/registry.access.redhat.com/ubi8/images/8.10-1088' 
	--label='vcs-ref=967861a8dbbb288b8cec9f1fee7ccbf6c7ee9a20' 
	--label='vcs-type=git' 
	--label='vendor=IBM' 
	--label='version=24.0.0.6' 
	--runtime=runc 
	--memory="4294967296" 
	--memory-reservation="4294967296" -d icr.io/cpopen/odm-k8s/odm:9.0`

**Comment by vandermerwewaj** [comment]
Finally got ODM Docker running again. increasing JVM to 3GB with the following:
`docker run -e LICENSE=accept  -m 4096M --memory-reservation 4096M -p 9060:9060 -p 9443:9443 -e SAMPLE=false -e JAVA_OPTS="-Xms3072M -Xmx3072M"  icr.io/cpopen/odm-k8s/odm:9.0`

**Comment by vandermerwewaj** [comment]
Any chance for a feature to indicate allocated, used and remaining free resources in like an ascii widget mimic during startup, maybe also shortlist of milestones indicating progress of components starting. Meh.

**Comment by lgrateau** [comment]
Hi, I don’t think manually setting the memory is ideal, as the JVM leverages the UseContainerSupport flag to allocate memory dynamically. You can read more about it here: UseContainerSupport documentation.

Could you let us know if the issue also occurs with the sample ruleset embedded in the image (set sample=true), or is it specific to your use case?

**Comment by vandermerwewaj** [comment]
> Hi, I don’t think manually setting the memory is ideal, as the JVM leverages the UseContainerSupport flag to allocate memory dynamically. You can read more about it here: UseContainerSupport documentation.
> 
> Could you let us know if the issue also occurs with the sample ruleset embedded in the image (set sample=true), or is it specific to your use case?

In this case, ODM didn't start up in the docker image.
Meaning even before I could try looking for or accessing the sample or login to ODM, the docker JVM had Out Of Memory errors.
I also redownloaded docker, ODM and still had issues.

**Comment by lgrateau** [comment]
Maybe you have to check the WSL memory allocated.
https://stackoverflow.com/questions/62405765/memory-allocation-to-docker-containers-after-moving-to-wsl-2-in-windows

**Comment by vandermerwewaj** [comment]
> Maybe you have to check the WSL memory allocated. https://stackoverflow.com/questions/62405765/memory-allocation-to-docker-containers-after-moving-to-wsl-2-in-windows

Already done that, also mentioned [above](https://github.com/DecisionsDev/odm-ondocker/issues/360#issuecomment-2468260419).

WSL was limited to 2GB, I then configured it to allocate  4GB and still had Out Of Memory errors.
Then I forced JVM to 3GB allowing ODM to start up.

**Comment by lgrateau** [comment]
Have you also configured the swap parameters?
Which Docker implementation are you using?

We haven’t been able to reproduce your issue when testing with Rancher and WSL on Windows. It seems that the JVM may not be detecting container awareness, which can sometimes happen if the Docker installation lacks proper CGROUP support. In the past, we’ve seen similar behavior when the JVM doesn’t recognize it’s running in a containerized environment.
